version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./api/.env.dev
    ports:
      - "5432:5432"

  api:
    build: ./api
    tty: true
    volumes:
      - ./api:/go/src
    ports:
      - '8000:8000'
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c 'pnpm install && pnpm dev'

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: null
